CREATE TABLE `ALBUM` (
  `idA` INTEGER,
  `titreA` VARCHAR(254),
  `datesortie` YEAR,
  `producteur` VARCHAR(254),
  PRIMARY KEY (`idA`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `ALBUM_COMPILATION` (
  `idAC` INTEGER,
  `description` VARCHAR(254)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `ALBUM_COMPILATION` ADD FOREIGN KEY (`idAC`) REFERENCES `ALBUM` (`idA`);

CREATE TABLE `ALBUM_LIVE` (
  `idAL` INTEGER,
  `concert` VARCHAR(254)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `ALBUM_LIVE` ADD FOREIGN KEY (`idAL`) REFERENCES `ALBUM` (`idA`);


CREATE TABLE `ALBUM_STUDIO` (
  `idAS` INTEGER,
  `nom_ingé_son` VARCHAR(254)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `ALBUM_STUDIO` ADD FOREIGN KEY (`idAS`) REFERENCES `ALBUM` (`idA`);

CREATE TABLE `CHANSON` (
  `idA` INTEGER,
  `idC` INTEGER,
  `titreC` VARCHAR(254),
  `date_création` YEAR,
  `idChanson` INTEGER,
  `typec` VARCHAR(254),
  `numero_piste` INTEGER,
  PRIMARY KEY (`idC`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `DÉCRIRE` (
  `idV` INTEGER,
  `idP` INTEGER,
  PRIMARY KEY (`idV`, `idP`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `FAIRE_PARTIE` (
  `idM` INTEGER,
  `idG` INTEGER,
  `date_debut` DATE,
  `rôle` VARCHAR(254),
  `membre_fondateur` TINYINT(1),
  PRIMARY KEY (`idM`, `idG`, `date_debut`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `GENRE` (
  `idGE` INTEGER,
  `nom_genre` VARCHAR(254),
  `idge_1` INTEGER,
  PRIMARY KEY (`idGE`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `GROUPE` (
  `idG` INTEGER,
  `nomG` VARCHAR(254),
  `date_formation` YEAR,
  `date_separation` YEAR,
  PRIMARY KEY (`idG`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `INCLURE` (
  `idLec` INTEGER,
  `idA` INTEGER,
  `numéro_de_piste` INTEGER,
  PRIMARY KEY (`idLec`, `idA`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `INTERPRÉTER` (
  `idV` INTEGER,
  `idC` INTEGER,
  `idG` INTEGER,
  PRIMARY KEY (`idV`, `idC`, `idG`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `JOUER` (
  `idLec` INTEGER,
  `idV` INTEGER,
  PRIMARY KEY (`idLec`, `idV`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `LIEU` (
  `idLieu` INTEGER,
  `nomLieu` VARCHAR(254),
  `coordonnéeX` INTEGER,
  `coordonnéeY` INTEGER,
  PRIMARY KEY (`idLieu`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `LISTE_DE_LECTURE` (
  `idLec` INTEGER,
  `titreLec` VARCHAR(254),
  `dateLec` DATE,
  PRIMARY KEY (`idLec`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `MUSICIEN` (
  `idM` INTEGER,
  `nomM` VARCHAR(254),
  `prenomM` VARCHAR(254),
  `nom_de_scène` VARCHAR(254),
  PRIMARY KEY (`idM`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `OEUVRE` (
  `idO` INTEGER,
  `nomoeuvre` VARCHAR(254),
  `idC` INTEGER,
  PRIMARY KEY (`idO`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PERIODE` (
  `date_debut` DATE,
  `date_fin` DATE,
  PRIMARY KEY (`date_debut`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `POSSÉDER` (
  `idC` INTEGER,
  `idGE` INTEGER,
  PRIMARY KEY (`idC`, `idGE`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PRODUIRE` (
  `idC` INTEGER,
  `idV` INTEGER,
  `datedeb` DATE,
  `datefin` DATE,
  PRIMARY KEY (`idC`, `idV`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PROPRIÉTÉ` (
  `idP` INTEGER,
  `filesize` INTEGER,
  `playcount` INTEGER,
  `lastplayed` INTEGER,
  `skipcount` INTEGER,
  PRIMARY KEY (`idP`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `SE_PRODUIRE` (
  `concert` VARCHAR(254),
  `idLieu` INTEGER,
  PRIMARY KEY (`concert`, `idLieu`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `VERSION` (
  `idV` INTEGER,
  `numéroV` INTEGER,
  `dateV` YEAR,
  `Durée` INTEGER,
  `nomfichier` VARCHAR(3000),
  PRIMARY KEY (`idV`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `COMPOSER` (
  `idG` INTEGER,
  `idO` INTEGER,
  PRIMARY KEY (`idG`, `idO`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ENREGISTRER` (
  `idG` INTEGER,
  `idV` INTEGER,
  PRIMARY KEY (`idG`, `idV`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `INVITER` (
  `idC` INTEGER,
  `idM` INTEGER,
  `commentaire` VARCHAR(254),
  PRIMARY KEY (`idC`, `idM`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `TYPE_RELATIONS` (
  `idChanson` INTEGER,
  PRIMARY KEY (`idChanson`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `DATES` (
  date DATE,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


ALTER TABLE `DÉCRIRE` ADD FOREIGN KEY (`idP`) REFERENCES `PROPRIÉTÉ` (`idP`);
ALTER TABLE `DÉCRIRE` ADD FOREIGN KEY (`idV`) REFERENCES `VERSION` (`idV`);
ALTER TABLE `FAIRE_PARTIE` ADD FOREIGN KEY (`date_debut`) REFERENCES `PERIODE` (`date_debut`);
ALTER TABLE `FAIRE_PARTIE` ADD FOREIGN KEY (`idG`) REFERENCES `GROUPE` (`idG`);
ALTER TABLE `FAIRE_PARTIE` ADD FOREIGN KEY (`idM`) REFERENCES `MUSICIEN` (`idM`);
ALTER TABLE `GENRE` ADD FOREIGN KEY (`idge_1`) REFERENCES `GENRE` (`idGE`);
ALTER TABLE `INCLURE` ADD FOREIGN KEY (`idA`) REFERENCES `ALBUM` (`idA`);
ALTER TABLE `INTERPRÉTER` ADD FOREIGN KEY (`idG`) REFERENCES `GROUPE` (`idG`);
ALTER TABLE `INTERPRÉTER` ADD FOREIGN KEY (`idC`) REFERENCES `CHANSON` (`idC`);
ALTER TABLE `INTERPRÉTER` ADD FOREIGN KEY (`idV`) REFERENCES `VERSION` (`idV`);
ALTER TABLE `JOUER` ADD FOREIGN KEY (`idV`) REFERENCES `VERSION` (`idV`);
ALTER TABLE `OEUVRE` ADD FOREIGN KEY (`idC`) REFERENCES `CHANSON` (`idC`);
ALTER TABLE `POSSÉDER` ADD FOREIGN KEY (`idGE`) REFERENCES `GENRE` (`idGE`);
ALTER TABLE `POSSÉDER` ADD FOREIGN KEY (`idC`) REFERENCES `CHANSON` (`idC`);
ALTER TABLE `PRODUIRE` ADD FOREIGN KEY (`idV`) REFERENCES `VERSION` (`idV`);
ALTER TABLE `PRODUIRE` ADD FOREIGN KEY (`idC`) REFERENCES `CHANSON` (`idC`);
ALTER TABLE `SE_PRODUIRE` ADD FOREIGN KEY (`idLieu`) REFERENCES `LIEU` (`idLieu`);
ALTER TABLE `COMPOSER` ADD FOREIGN KEY (`idO`) REFERENCES `OEUVRE` (`idO`);
ALTER TABLE `COMPOSER` ADD FOREIGN KEY (`idG`) REFERENCES `GROUPE` (`idG`);
ALTER TABLE `ENREGISTRER` ADD FOREIGN KEY (`idV`) REFERENCES `VERSION` (`idV`);
ALTER TABLE `ENREGISTRER` ADD FOREIGN KEY (`idG`) REFERENCES `GROUPE` (`idG`);
ALTER TABLE `INVITER` ADD FOREIGN KEY (`idM`) REFERENCES `MUSICIEN` (`idM`);
ALTER TABLE `INVITER` ADD FOREIGN KEY (`idC`) REFERENCES `CHANSON` (`idC`);
